apiVersion: v1
kind: Template
metadata:
  name: jenkins-lab
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAMESPACE}
      name: ${APP_NAMESPACE}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAMESPACE}
        deploymentconfig: ${APP_NAMESPACE}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAMESPACE}
            deploymentconfig: ${APP_NAMESPACE}
        spec:
          containers:
          - image: ${APP_IMAGE}
            imagePullPolicy: Always
            name: ${APP_NAMESPACE}
            ports:
            - containerPort: 8080
              protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
      triggers:
        - type: ConfigChange
        - type: "ImageChange"
          imageChangeParams:
            automatic: true 
            from:
              kind: "ImageStreamTag"
              name: ${APP_IMGS}
              namespace: ${DEV_NAMESPACE}
            containerNames:
              - ${APP_NAMESPACE}

  - apiVersion: v1
    kind: Service
    metadata:
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAMESPACE}
      name: ${APP_NAMESPACE}
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: ${APP_NAMESPACE}
        deploymentconfig: ${APP_NAMESPACE}
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAMESPACE}
      name: ${APP_NAMESPACE}
    spec:
      host: ${APP_URL}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APP_NAMESPACE}
        weight: 100
      wildcardPolicy: None
      

      
parameters:
  - name: APP_IMAGE
    required: true
  - name: APP_IMGS
    required: true
  - name: APP_URL
    required: true
  - name: DEV_NAMESPACE
    required: true
  - name: APP_NAMESPACE
    required: false
    value: "appjava"
  - name: GIT_URL
    required: false
    value: "http://gogs-op.io/gogs/openshift-jee-sample.git"
    